### ISSUE TITLE
what do the parameters "--fillonly" and "--joinonly" mean?

### ISSUE THREAD

**Issue by hui-liu** [aaranyue/quarTeT#12]
Hi,
I failed to understand the parameters "--fillonly" (Only fill the gaps without join) and "--joinonly" (Only join the gaps without fill), could you give me more explanation? Thanks!

**Comment by Echoring** [comment]
There are two ways to close a gap. "fill" means find a segment that can be placed in the gap and link them together. "join" means find an evidence that the gap edge is overlaped and can be directly merged into one. (for now, "join" is not as stable as "fill")
