### ISSUE TITLE
Could I generate haplotype-resolved assembly using AssemblyMapper?

### ISSUE THREAD

**Issue by hui-liu** [aaranyue/quarTeT#13]
Hi,

Thanks for developing the nice package.

(1) I have two contig-level phased assembles, including `{prefix}.bp.hap1.p_ctg.fasta` and `{prefix}.bp.hap2.p_ctg.fasta`, generated by `hifiasm` with HiFi reads. If I have a closely related reference genome (`ref.fasta`), should I run the AssemblyMapper as following commands?

`python3 quartet.py AssemblyMapper -r ref.fasta -q  {prefix}.bp.hap1.p_ctg.fasta` 
`python3 quartet.py AssemblyMapper -r ref.fasta -q  {prefix}.bp.hap2.p_ctg.fasta` 

(2) In addition, if have a closely related reference genome that is haplotype-resolved (`ref_hapA.fasta` and `ref_hapB.fasta`), I am wondering if could I generate a haplotype-resolved assembly based on the closely related reference genome?

Thanks!

**Comment by Echoring** [comment]
1. YES.
2. You can merge the two reference to one ref.fasta, and do the same as (1). Half of reference will fail to be mapped (or mapped by only some short contigs), indicating the belongings.
