### ISSUE TITLE
"Np.contig_map_ref.gp", line 40733: unrecognized option - see 'help set'.

### ISSUE THREAD

**Issue by wangjie07070910** [aaranyue/quarTeT#15]
This tool looks great and I'm exploring it, but I'm having the following issues while using it, and I'd appreciate it if you could assist me with it.
**[Info] Paramater:** refgenomefile=Np.fasta, mincontiglength=50000, minalignmentlength=10000, minalignmentidentity=0.9, prefix=Np_14703, threads=40, aligner=minimap2, nofilter=False, plot=False, overwrite=False, nucmeroption=, deltafilteroption=, minimapoption=-x asm5 -t 40
[Info] Filtering contigs input...
[Info] Checking telomere in contigs...
[Info] Running minimap2...
[Error] Unexcepted error occur in gnuplot as follow:
cmd: gnuplot Np.contig_map_ref.gp
returncode: 1
stdout:

stderr:

set mouse format "%.0f"
    ^
"Np.contig_map_ref.gp", line 40733: unrecognized option - see 'help set'.

**But I checked this file and it doesn't have line 40733 at all**

 vi +40733 Np.contig_map_ref.gp
-c option, 1: Illegal address: only 39567 lines in the file

**Comment by Echoring** [comment]
I cannot make sure about this. Maybe this is an issue with incompatible gnuplot? Or png terminal not supported? By the way, too many sequence sometimes also cause error when ploting.

**Comment by kazumaxneo** [comment]
Hello
I got same error.
 I have not specified any options for --plot but I am getting this.
Could you Kindly provide an option to disable plotting?
I am using the latest version 1.1.8.

$ python3 quartet.py AssemblyMapper -q hifiasm.fasta -r GCF_001433935.1.fasta -t 40 -a minimap2 --plot
[Info] Paramater: refgenomefile=GCF_001433935.1.fasta, qryfile=hifiasm.fasta, mincontiglength=50000, minalignmentlength=10000, minalignmentidentity=0.9, prefix=quarTeT, threads=40, aligner=minimap2, nofilter=False, plot=True, overwrite=False, nucmeroption=, deltafilteroption=, minimapoption=-x asm5 -t 40
[Info] Filtering contigs input...
[Info] Checking telomere in contigs...
[Info] Running minimap2...
[Error] Unexcepted error occur in gnuplot as follow:
cmd: gnuplot quarTeT.contig_map_ref.gp
returncode: 1
stdout:

stderr:

set mouse format "%.0f"
    ^
"quarTeT.contig_map_ref.gp", line 133: unrecognized option - see 'help set'.

**Comment by Echoring** [comment]
It most likely to be that the compiled gnuplot is not compatible with the quarTeT. I'm not sure what is lacking. This figure is a dotplot showing the colinearity between contigs and reference genome. If you do not require such a plot, try new option `--noplot` in v1.2.0.
