### ISSUE TITLE
png输入问题

### ISSUE THREAD

**Issue by zongzone** [aaranyue/quarTeT#16]
您好，我这边使用的是1.14最新版本 运行完没有报错，但是发现没有png图片的输出，也没有发现svg图片的输出
![image](https://github.com/aaranyue/quarTeT/assets/101814626/d7b70c71-2b2c-4bae-84d0-ae4e5da392c4)
![image](https://github.com/aaranyue/quarTeT/assets/101814626/cf063a2f-9c77-4b11-ab97-de65a6c6d4a2)

**Comment by Echoring** [comment]
我无法确定错误，鉴于没有svg成功输出，这可能是R出了问题。
你可删去`quartet_util.py`文件中第275行，再运行一次程序，然后进入tmp文件夹手动执行`Rscript genomedrawer.r`，看R报什么问题。我在程序中只检索了含有`Execution halted`的错误，可能有些我没考虑的其他情况。
