### ISSUE TITLE
How AssemblyMapper ensure the genome is complete.

### ISSUE THREAD

**Issue by xiekunwhy** [aaranyue/quarTeT#17]
Hi,

In my opinion, T2T genome is a near complete genome.

After reading the quarTeT paper, I feel that AssemblyMapper is just a simpler version of RagTag(https://github.com/malonge/RagTag), what effort AssemblyMapper has been made to ensure the results is a complete genome? 

If AssemblyMapper is just a reference guided anchor tools, what effort can we do to get a genome as complete as possible (I know I can use verkko, but it is time consuming).

Best,
Kun

**Comment by Echoring** [comment]
AssemblyMapper indeed is a reference-guided anchor tool. The completeness of resulting draft genome depends on the quality of reference. The using cases assumed in design is assembly of an update of a complete genome. AssemblyMapper also collect the contigs with telomeres and place them at both ends to improve the completeness. To improve the completeness, better contig continuity and reference quality is needed (and at most time unavailable). In fact AssemblyMapper do no better than RagTag scafford, just a little improvement combining telomere identification.
