### ISSUE TITLE
着丝粒可视化bug

### ISSUE THREAD

**Issue by btrainee** [aaranyue/quarTeT#18]
hi , 
quarTeT软件是做T2T基因组非常棒的软件，近期在使用着丝粒预测功能时，发现candidate结果文件没有按照染色体自然数排序，导致后续在画图的时候编号识别错误，如chr10识别为2号，chr11识别为3号染色体
![image](https://github.com/aaranyue/quarTeT/assets/40187286/b8d9f615-924d-44f5-ac99-a96f56284270)
![image](https://github.com/aaranyue/quarTeT/assets/40187286/4c04795f-1c57-49c8-bdb4-9558a3ef17ce)

感谢您的工作，如确实存在以上问题，建议可以修正，
祝好

**Comment by Echoring** [comment]
实际上CentroMiner中并没有包含排序染色体的功能，作图的时候只是按源fasta的顺序编号的，这种情况是否可能是因为在输入的文件中染色体的排序就不是按自然数排的？

**Comment by btrainee** [comment]
> 实际上CentroMiner中并没有包含排序染色体的功能，作图的时候只是按源fasta的顺序编号的，这种情况是否可能是因为在输入的文件中染色体的排序就不是按自然数排的？

源fasta确实没有排序，问题是如果不进行排序的话生成的chr.txt中编号将会发生变化，10号变成2号，同时生成的图编号也不是真实的了。现在情况也就是要求源fasta得按照自然数排序才能避免这个问题了吧？

**Comment by Echoring** [comment]
是的，我们假定输入的文件是排过序的，因为在名字里体现染色体编号的方法实在是千奇百怪，难以统一处理。
