### ISSUE TITLE
About references guided assemble

### ISSUE THREAD

**Issue by xiekunwhy** [aaranyue/quarTeT#2]
Hi,

1. Can I use hifiasm p_ctg + hic anchor result as reference genome when using AssemblyMapper ? It is very hard to get a close-related reference genome when assembling some "new" species.
2. What assemble level of reference genome is required ? Gap free T2T ?

Best,
Kun

**Comment by Echoring** [comment]
It's good to use hic anchored scafford as reference. We used the same stat. 
Reference genome can be any, even not a genome such as hic scafford.

**Comment by xiekunwhy** [comment]
Ok, I will try it, thank you for your reply!
