### ISSUE TITLE
[Error] No gap can be closed

### ISSUE THREAD

**Issue by Bank-tidy** [aaranyue/quarTeT#23]
Hello,
Thank you for developing a very useful tool,I have some doubts about using the tool, so I woulld like to ask you for advice:

The contigs I entered using the -g parameter are contigs assembled by hifiasm, not the original sequencing fastq files. The -d parameter genome is the conitgs assembled by hifiasm and then the ragtag is mounted on the reference genome. Is this correct?

- These are my eight gaps areas：

```
Type	Shape	Chr	Start	End	color
gap	box	1	34169914	34170013	ff7f00
gap	box	1	34334335	34334434	ff7f00
gap	box	1	34407737	34407836	ff7f00
gap	box	1	34524188	34524287	ff7f00
gap	box	7	69516260	69516359	ff7f00
gap	box	7	69567308	69567407	ff7f00
gap	box	8	60420099	60420198	ff7f00
gap	box	9	33288797	33288896	ff7f00
```

- This is my script：

`python3 /public1/home/yinhang/software/apps/quarTeT/quartet.py GapFiller -d ${hifiasm_genome} -g ${hifiasm_contigs} -t 60 -p tomato_gap`

- This is my error：

```
[Info] Paramater: draftgenomefile=~/tomato_t2t_N0.fasta, gapclosercontigfilelist=[~/SL50_hifiasm_all.fa'], flanking=5000, minalignmentlength2=1000, minalignmentidentity2=0.4, maxfillinglen=1000000, prefix=tomato_gap, threads=60, minimapoption=-x asm5 -t 60, overwrite=False, enablejoin=False, joinonly=False
[Info] Getting gaps flanking sequence...
[Info] gapfilling with SL50_hifiasm_all.fa...
[Info] Running minimap2...
[Info] Analysising Alignments...
[Info] All files processed.
[Error] No gap can be closed.
```

Looking forward to your reply,
Best wishes

**Comment by Echoring** [comment]
Are you using contigs from hifiasm to close gaps in a genome assembled by the same contigs?
These same contigs cannot provide information that can be used to close the gaps.
You should use sequences from other source to do this. (e.g. raw reads, ONT, other contig assembly tools)
Meanwhile, quarTeT currently not support fastq format. If you want to use raw reads to close the gaps, you should change them to fasta format.

**Comment by Echoring** [comment]
This error is not reported by quarTeT, but your computer. Seems your computer is out of memory. 
Meanwhile, NGS reads is too short to give information for gapclosing. Use longer assembly.

**Comment by Bank-tidy** [comment]
Thanks for your suggestion！
I'll try it again
