### ISSUE TITLE
Confused about CloserScore

### ISSUE THREAD

**Issue by Bank-tidy** [aaranyue/quarTeT#25]
Dear the author,

Thank you for developing such a useful program. I have been using GapFiller to fill gaps in my genome assembly at the scaffold level. However, I found that, although I achieved a decent score of 1.97, the alignment results of these reads using Minimap2 and BLAST are relatively poor. Do you have any recommendations for this issue?
![image](https://github.com/aaranyue/quarTeT/assets/108465040/03aae414-ab85-4c4a-ba76-5920b3961716)
<img width="517" alt="a8e9b62661bdc3001ef16dbcd78d634" src="https://github.com/aaranyue/quarTeT/assets/108465040/eff83de9-4a30-4284-b5e7-d08fb5675ce0">

Best,
Bank

**Comment by Echoring** [comment]
By default, quarTeT GapFiller requires >1000 bp alignment with >40% identity at both frank 5000 bp to fill the gap.
Score 1.97 means the identity of the two alignments are high. In your case, I assume that the alignment is a little far from the gap.
If you feel unproper, you can increase `-l` or decrease `-f` to restrict the alignment more near the gap.

**Comment by Bank-tidy** [comment]
@Echoring Oh, I understand, thank you for your answer!
