### ISSUE TITLE
What sequence should I use to visualise the centromere

### ISSUE THREAD

**Issue by shehongbing** [aaranyue/quarTeT#29]
Hi,
     Thanks for your powerful tool.  I have a question about the Centromere module. 

I get the best candidate centromeres, as follows (using Chr4 as an example, the Chr4 with a centromere of 65 Mb-66 Mb),

```
Chr4    65897059        66008690        111632  11816   10.58%  98649   88.37%  0.19421934767224158
Chr4@TR_03018   200     1338    1.2%
Chr4@TR_00285   183     1070    0.96%
Chr4@TR_01112   167     1060    0.95%
Chr4@TR_00608   166     953     0.85%
Chr4@TR_00650   130     757     0.68%
...
```
Then, I extracted all of above TR  from the GFF3 file (TRgff3/*Chr4.tr.blast.gff3) and visualised  it in IVG, however, I cannot obtain corresponding centromere at 65 Mb-66 Mb (see below).
![image](https://github.com/aaranyue/quarTeT/assets/49432965/25b8423c-5752-4ffc-9e33-46697cb4fdac)

Thus, What sequence should I use to visualise the centromere.

Thx
Hongbing

**Comment by Echoring** [comment]
Right click and select Expanded mode, and enlarge the viewing region focus on the candidate region may be of help. 
Meanwhile, the best candidate is just a prediction. It's highly recommended to check other candidates, and combine TR, TE, and gene content, Hi-C heatmap, pairwise colinearity etc. to vote your candidates.
