### ISSUE TITLE
The difference between join and fill mode?

### ISSUE THREAD

**Issue by Marison-1** [aaranyue/quarTeT#33]
hi!Thank you very much for sharing this nice tools! I used the gapfill module for my data, and I noticed that there are two mode of this module(join and fill), they have a different result of gap filling.

In conclusion, I wonder that what's the different between join and fill mode of gap filling? And why join-mode closed gap has a CloserTigID but a 0 CloserLength in [detail file]!

thanks again!

**Comment by Echoring** [comment]
`fill` means find a segment that can be placed in the gap and link them together. `join` means find an evidence (a sequence) that the gap edge is overlaped and can be directly merged into one (so closerlength is 0). For now, join mode is unstable and disabled by default. If you want to enable it, be careful and check the result manually.
