### ISSUE TITLE
 Input genome does not have valid gap

### ISSUE THREAD

**Issue by yghyghyghyghygh** [aaranyue/quarTeT#37]
你好，使用GapFiller模块提示" Input genome does not have valid gap",需要填充的gap的draft genomes是由wtdbg2组装的，-g数据是fastq转换成的fasta。这种问题改怎么解决，谢谢。
![QQ图片20240602214939](https://github.com/aaranyue/quarTeT/assets/117809784/bfd184d0-f2cd-4710-a376-96cd7e53c428)

**Comment by Echoring** [comment]
该模块默认将>100个N识别为gap，如果draft genome组装软件输出的gap表示方法不同，便可能出现该错误，请检查draft genome。

**Comment by yghyghyghyghygh** [comment]
好的，谢谢帮助
