### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/sx_tm.txt'

### ISSUE THREAD

**Issue by HaoWenhy** [aaranyue/quarTeT#4]
Hello, thank you very much for developing this software, which can help me solve some problems. I want to identify telomere sequence information through linux commands, but in the process of my use, according to the parameter Settings, the running time will always report an error, I do not know how to solve.

How should this be resolved?  Looking forward to your reply. Thank you.

**Comment by Echoring** [comment]
This happened most likely that `tidk explore` failed.
Make sure that tidk is accessable in $PATH. 
Also make sure that the version is below the newest 0.2.31, this version updated after our program design and make great changes in `tidk explore` module. quarTeT currently do not surport.
