### ISSUE TITLE
Can AssemblyMapper keep contigs which are not mapped to pseudomolecules, like ragtag does?

### ISSUE THREAD

**Issue by yaoxkkkkk** [aaranyue/quarTeT#41]
Thank you for you development. I just want to keep all contigs not only chromosomes, ragtag could keep unmapped contigs and can organise them to chr00. I wonder whether quarTeT had similar function?

**Comment by Echoring** [comment]
This is added in just released V1.2.2. With new option '--keep', the unplaced contigs will also be included in the draft genome. (not merged as chr00 though)

**Comment by yaoxkkkkk** [comment]
Thank you for your very soon update.
