### ISSUE TITLE
[suggestion] Add telomere parameter at quartet_assemblymapper.py

### ISSUE THREAD

**Issue by a927050047** [aaranyue/quarTeT#45]
I noticed that in the ‘quartet_assemblymapper.py’ file, there is a command ‘python3 {sys.path[0]}/quartet_teloexplorer.py -i {contigfile} -p {prefix}.tig --noplot’ used to identify ‘monopolize’, ‘forceleft’, and ‘forceright’ contigs. It would be more accurate if we could specify the telomere sequence(like -c plant in the quartet_teloexplorer.py) instead of having it chosen automatically.

**Comment by Echoring** [comment]
Implemented in v1.2.4. Thanks for suggestion!
