### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'tmp/sx_tm.txt'

### ISSUE THREAD

**Issue by HaoWenhy** [aaranyue/quarTeT#5]
Hello, thank you very much for developing this software, which can help me solve some problems. I want to identify telomere sequence information through linux commands, but in the process of my use, according to the parameter Settings, the running time will always report an error, I do not know how to solve.
How should this be resolved? Looking forward to your reply. Thank you.
![1](https://github.com/aaranyue/quarTeT/assets/137880289/4a04deea-0973-438b-9a33-7769401fb9fc)
![2](https://github.com/aaranyue/quarTeT/assets/137880289/d449fc9f-c9c3-4a03-b6c8-a40ed1c2d3f6)

**Comment by Echoring** [comment]
This happened most likely that `tidk explore` failed.
Make sure that tidk is accessable in $PATH.
Also make sure that the version is below the newest 0.2.31. This version updated after our program design and make great changes in `tidk explore` module. quarTeT currently do not support it. Please use version 0.2.1 instead.

**Comment by HaoWenhy** [comment]
Thank you very much, I just checked my tidk, it is indeed version 0.2.31, I will give it a lower version and try again.
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/3/2023 16:52
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [aaranyue/quarTeT] FileNotFoundError: [Errno 2] No such file or directory: 'tmp/sx_tm.txt' (Issue #5)
        
      
    
  

This happened most likely that tidk explore failed.
Make sure that tidk is accessable in $PATH.
Also make sure that the version is below the newest 0.2.31. This version updated after our program design and make great changes in tidk explore module. quarTeT currently do not support it. Please use version 0.2.1 instead.

**Comment by HaoWenhy** [comment]
Hello, after yesterday's guidance to downgrade tidk, I successfully identified its telomeres and centromere, and there were corresponding results, but no.png format picture appeared, and no error information was reported, I don't know why, please answer! thank you

**Comment by HaoWenhy** [comment]
Hello, after yesterday's guidance to downgrade tidk, I successfully identified its telomeres and centromere, and there were corresponding results, but no.png format picture appeared, and no error information was reported, I don't know why, so I would like to consult you again! thank you

**Comment by Echoring** [comment]
This may due to an error of R. Was R package `RIdeogram` successfully installed in the R in `$PATH`?
Or is there large amount of gaps (>100) exist in the genome?
(and what's your version of quarTeT? I remembered I have add a warning when figure drawing is failed in v1.0.3)

**Comment by HaoWenhy** [comment]
oh, my quarTeT was v1.0.2, so didn't see any information about graph drawing failures
        
    
         
        
            
                        ***@***.***
            
        
     
        
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            ***@***.***>
            
        
      
      
        
         Date 
        
        
        7/4/2023 09:16
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [aaranyue/quarTeT] FileNotFoundError: [Errno 2] No such file or directory: 'tmp/sx_tm.txt' (Issue #5)
        
      
    
  

This may due to an error of R. Was R package RIdeogram successfully installed in the R in $PATH?
Or is there large amount of gaps (>100) exist in the genome?
(and what's your version of quarTeT? I remembered I have add a warning when figure drawing is failed in v1.0.3)
