### ISSUE TITLE
usage issues

### ISSUE THREAD

**Issue by zhangwenda0518** [aaranyue/quarTeT#6]
Thanks teacher, for developing the easy to use T2T assembly tool

I ran GapFiller on my assembly result combined with hifi data, maybe I ran TGS-GapCloser in the previous step and wasn't able to continue to make up the gap。
I have a question, the parameter **-g GAPCLOSER_CONTIG [GAPCLOSER_CONTIG ...]**  refers to the result of the assembly using other software or the data used for the assembly?

I also used TeloExplorer and CentroMiner to get the following graphs. I found a problem with the legend-length scale, but I can't find the parameters to modify it.

Also, for centromere positioning, is it possible to show the centromere length range? My species is supposed to be a long centriolar species, and I want to determine its length, can you give me some advice?

Thanks！

![image](https://github.com/aaranyue/quarTeT/assets/77140740/566c827c-a97d-44be-b785-f521e7943bc7)

![image](https://github.com/aaranyue/quarTeT/assets/77140740/74bca002-cc1b-4138-821d-aa3501df0fd7)

**Comment by Echoring** [comment]
1. GAPCLOSER_CONTIG can use either assembled contigs or raw reads (should be FASTA format). However, the quality of gapfilling will be better when well assembled contigs are input. If you use Hi-Fi data to close gaps, you can assemble them using hifiasm software (https://github.com/chhylp123/hifiasm).
2. the legend-length scale is not by our design. The figure drawn by ourselves have no such scale, so you'd better check your R.
3. The centromere length is shown in the 4th collum of *.candidate. You can collect them like this: `grep ^$'\t' -v *.candidate | cut -f 4`

**Comment by zhangwenda0518** [comment]
Thanks for your quick reply.
As for the first question, I have another one question. I have used quickmerge and RagTag to lift the assembled N50. Is the principle of filling holes in quarTeT using assembled contigs similar to them? What I care about is whether quarTeT is more suitable for application after hic mounting? Anyway, quarTeT is more convenient to use.

The second question, the question of scale。 The dependency program Rideogram that I installed locally before is RIdeogram_0.2.3.tar.gz, https://github.com/TickingClock1992/RIdeogram_test.
This version has the function of scale. 
I modified the file quartet_util.py, and added the adjustment parameter Ruler = 5 according to the size of my genome, and the display is normal.
quartet_util.py:251:ideogram(karyotype = chr, label = label, label_type = "marker",Ruler = 5)
quartet_util.py:257:ideogram(karyotype = chr,Ruler = 5)
![image](https://github.com/aaranyue/quarTeT/assets/77140740/35b3ca4c-1903-4f8e-ac73-6daf41f044bd)

**Comment by Echoring** [comment]
The strategy of these program are mainly the same, only minor difference are applied.
I haven't compared with quickmerge. As for RagTag, its “patch” tool applies an aggressive strategy that may discard variation or insert large segments to ultimately close the gaps. Conversely, the quarTeT "GapFiller" adopts a conservative strategy and never modifies the raw sequence to avoid variation loss.
For short, RagTag is better for closing more gaps, however, quarTeT is more accurate.

The designed workflow of quarTeT is using Hi-C data to scafford pseudo-chromosomes as reference, and use AssemblyMapper to assemble a draft genome,  then use GapFiller to close the gaps. However, as the reference genome is highly homologous, it can also be used.
