### ISSUE TITLE
能够提交数据但最终结果是空的

### ISSUE THREAD

**Issue by XXH123a** [aaranyue/quarTeT#9]
您好，请问在使用补gap这个功能时，传输数据正常，提交后也收到作业ID，但输入ID后并没有任何结果怎么办呢？必须本地安装运行吗?呜呜

**Comment by Echoring** [comment]
请问你的job ID？我看一下具体情况

**Comment by XXH123a** [comment]
GapFill_eda3b36e-a160-4666-a644-ed940e512257
试了四次，这是第四次的

**Comment by Echoring** [comment]
问题似乎出在文件过大，服务器内存不足，导致minimap2比对异常终止。
此外我发现了错误报告方面的很多问题，我需要一些时间来解决。
我用其他服务器为你强行运行了任务，暂作权宜之计：GapFill_eda3b36e-a160-4666-a644-ed940e512257

**Comment by Echoring** [comment]
我尝试减少了内存占用，但仍然不足以运行你的任务。
建议本地安装，或者考虑把输入文件分成多个进行操作。
我已经修复了报错模块，现在比对失败时应该能正常报错了。

**Comment by XXH123a** [comment]
非常感谢，conda安装快速简单，本地运行很快没有报错，只不过PNG和SVG乱码，不能显示，还是需要手动Rideogram画一下，在我的数据中降低比对值对结果没有影响，填充后剩余个位数的gap，想请教一下，如果用纯二代数据组装一个基因组再去填充，gapfiller是否能够运行？

**Comment by Echoring** [comment]
用纯二代数据组装的基因组一般会有非常多的gap，GapFiller不太适合用于这种情况。
GapFiller假设基因组草图是通过三代数据构建，已经具有相当的质量。
